// Generated by auto imports
export {}
declare global {
  const ChartUIToolInvocation: typeof import('../../shared/utils/tools/chart').ChartUIToolInvocation
  const FILE_UPLOAD_CONFIG: typeof import('../../shared/utils/file').FILE_UPLOAD_CONFIG
  const FileWithStatus: typeof import('../../shared/utils/file').FileWithStatus
  const WeatherUIToolInvocation: typeof import('../../shared/utils/tools/weather').WeatherUIToolInvocation
  const chartTool: typeof import('../../shared/utils/tools/chart').chartTool
  const createError: typeof import('../../node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const getFileIcon: typeof import('../../shared/utils/file').getFileIcon
  const getRouteRules: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const parseMarkdown: typeof import('../../node_modules/@nuxtjs/mdc/dist/runtime/parser').parseMarkdown
  const removeRandomSuffix: typeof import('../../shared/utils/file').removeRandomSuffix
  const setResponseStatus: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const stringifyMarkdown: typeof import('../../node_modules/@nuxtjs/mdc/dist/runtime/stringify').stringifyMarkdown
  const useAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').useAppConfig
  const useRuntimeConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
  const weatherTool: typeof import('../../shared/utils/tools/weather').weatherTool
}